Mijn-7359 erfpacht vernise
Amsterdam/mijn-amsterdam-frontend pull request #1100
Opened 2023-12-18 07:54 UTC by timvanoostrom

2024-01-09 11:12 UTC, OscarBakker requested changes
Looks good, just a few questions

2024-01-09 11:12 UTC, OscarBakker commented on src/client/pages/Erfpacht/DossierDetail/DossierDetail.test.tsx
> +  // test('Renders Dossier Detailpage with error', async () => {
remove it? or will be needed later?

2024-01-09 11:12 UTC, OscarBakker commented on src/client/pages/Erfpacht/DossierDetail/ErfpachtDossierDetail.tsx
> +  const [dossier, api] = useAppStateBagApi<ErfpachtV2DossiersDetail>({
Name of AppStateBag is ok to me btw!

2024-01-09 11:12 UTC, OscarBakker commented on src/client/pages/Erfpacht/ErfpachtFacturen.test.tsx
> +  // test('Renders Facturen List Page with data on a small screen device', () => {
used later on?

2024-01-09 11:12 UTC, OscarBakker commented on src/client/pages/Erfpacht/erfpachtData.hook.ts
> +    // colStyles: {} as any,
removable?

2024-01-09 11:12 UTC, OscarBakker commented on src/client/styles/main.scss
> +  font-size: var(--mams-font-size-rem-adjust); // translates to 10px which makes 1rem = 10px in all other elemens contained within body
typo *elements

2024-01-09 11:12 UTC, OscarBakker commented on src/client/styles/main.scss
> +  // &:visited {
removable?

2024-01-09 12:06 UTC, timvanoostrom commented on src/client/components/CollapsiblePanel/CollapsiblePanel.tsx
> +      <Heading level={3} size="level-2">
Dat was ook mijn eerste gedachte maar het is gedaan, denk ik, om expliciet het verschil tussen level (H2/3/4/5) en font-grootte aan te geven. Makkelijker redeneren.

2024-01-09 12:06 UTC, timvanoostrom commented on src/client/components/CollapsiblePanel/CollapsiblePanel.tsx
> +export function CollapsiblePanelHeading({
Why?

2024-01-09 12:10 UTC, timvanoostrom commented on src/client/components/AutoLogoutDialog/AutoLogoutDialog.test_.tsx
> +  let listenerSpy: MockInstance;
Met Jest was het een spy, ik heb alleen de types aangepast. Het is, denk ik, niet nodig om overal die variabele namen aan te passen. Het begrip Spy is well known in front-end tests toch?

2024-01-09 12:10 UTC, timvanoostrom commented on src/client/hooks/useAppState.test.tsx
> +  let dataApiSpy: MockInstance;
Zie eerdere comment

2024-01-09 15:14 UTC, timvanoostrom commented on src/client/components/LinkToListPage/LinkToListPage.tsx
> +  label?: string;
Beide kan ook :-)

2024-01-09 15:15 UTC, timvanoostrom commented on src/client/components/ListPagePaginated/ListPagePaginated.tsx
> +  const { page = '1' } = useParams<{
zou kunnen. Je kunt er een story voor maken.

2024-01-11 09:47 UTC, OscarBakker commented on src/client/components/CollapsiblePanel/CollapsiblePanel.tsx
> +export function CollapsiblePanelHeading({
but okay if you prefer it this way

2024-01-11 09:48 UTC, OscarBakker approved these changes
after mc fix, its should be ok!

2024-01-12 12:55 UTC, merged