Mijn-9147-feature/fe 2 x parkeervergunningen tonen parkeren patroon c
Amsterdam/mijn-amsterdam-frontend pull request #1547
Opened 2024-10-17 12:21 UTC by OscarBakker

2024-10-17 14:52 UTC, timvanoostrom reviewed
Volgens mij kun je dit heel simpel houden:

```
{
    title: ThemaTitles.PARKEREN,
    id: Themas.PARKEREN,
    to: (appState: AppState) => {
      const hasParkerenVergunningen = (
        appState.VERGUNNINGEN?.content ?? []
      ).some((vergunning) =>
        PARKEER_CASE_TYPES.has(vergunning.caseType as DecosCaseType)
      );
      const urlExternal =
        appState.PARKEREN.content?.url ??
        import.meta.env.REACT_APP_SSO_URL_PARKEREN;
      return hasParkerenVergunningen ? AppRoutes.PARKEREN : urlExternal;
    },
    profileTypes: ['private', 'commercial'],
  },
```

in `thema.ts` kun je dan die ternary voor patroonC weglaten. 

Er is dan nog één klein issue en dat is de rel: 'external' prop voor externe urls. Je zou hiervoor een aanpassing kunnen maken in `MainNavSubmenu.tsx:34` 

```
return rel?.includes('external') || to.startsWith('http') ? (
```

2024-10-21 14:43 UTC, Anouk91 requested changes
Als ik op een vergunning klik, dus naar detail pagina wil
1. blijft hij lokaal eindeloos laden. 
2. en ik zie de breadcrum naar "Vergunningen en ontheffingen" en ontheffingen ipv "Parkeren"
![image](https://github.com/user-attachments/assets/1397e988-1c66-42a2-b044-7136c8c22717)

2024-10-22 11:48 UTC, OscarBakker commented on src/client/pages/Parkeren/useParkerenData.hook.tsx
> +    isLoading: isLoading(VERGUNNINGENv2),
deze moeten nog even aangepast zie ik

2024-10-22 12:06 UTC, timvanoostrom commented on src/client/pages/Parkeren/Parkeren.tsx
> +          </MaLink>
Een <button/> is geen valide child element van. een <a/>. Er kan hier een button gebruikt worden.

```
<Button
  variant="primary"
>
  Button label
  <Icon
    size="level-5"
    svg={function ra(){}}
  />
</Button>
```

https://designsystem.amsterdam/?path=/docs/components-buttons-button--docs

2024-10-22 12:06 UTC, timvanoostrom commented on src/client/pages/VergunningenV2/VergunningDetail.tsx
>          title: ThemaTitles.VERGUNNINGEN,
```suggestion
        title: backLink.title,
```

2024-10-22 12:06 UTC, timvanoostrom commented on src/universal/config/routes.ts
> +  'PARKEREN/DETAIL': '/parkeren/:title/:id',
Wat is `:title` hier?

2024-10-22 14:13 UTC, timvanoostrom commented on src/client/pages/Parkeren/useParkerenData.hook.tsx
> +
```suggestion
const vergunningenState = FeatureToggle.vergunningenV2Active ? VERGUNNINGENv2 : VERGUNNINGEN;
```

2024-10-22 14:15 UTC, timvanoostrom commented on src/client/pages/Parkeren/useParkerenData.hook.tsx
> +      : isError(VERGUNNINGEN),
```suggestion
    isLoading:  isLoading(vergunningenState),
    isError: isError(vergunningenState),
```

2024-10-22 14:17 UTC, timvanoostrom commented on src/client/pages/Parkeren/useParkerenData.hook.tsx
> +    : getFilteredVergunningen(VERGUNNINGEN.content);
```suggestion
  const parkeervergunningen = getFilteredVergunningen(vergunningenState.content);;
```

2024-10-22 14:58 UTC, timvanoostrom approved these changes

2024-10-22 15:09 UTC, merged