Mijn-8175-feature/parkeren evs aansluiting
Amsterdam/mijn-amsterdam-frontend pull request #1580
Opened 2024-11-06 12:50 UTC by OscarBakker

2024-11-07 07:59 UTC, timvanoostrom reviewed
Volgens mij is deze implementatie niet helemaal wat er gevraagd wordt / nodig is. Naast de code opmerkingen hier wat algemene:

Kun je de demo01.ams.fo.geodeci.fr domeinnaam in linkjes vervangen met example.org (oid)?

De data uit de vergunningen api hoeft vooralsnog niet in de FE te verschijnen. Daarnaast is de implementatie van het sturen van de data naar de frontend niet helemaal zoals we dat normaal gesproken zouden doen (zie comment in betreffende code).

Je kunt de implementatie beter doen aan de hand van `isKnown: boolean`

```
const isKnown = hasPermits || hasPermitRequests;
```

2024-11-07 07:59 UTC, timvanoostrom commented on mocks/routes/parkeren.js
> +                link: 'demo01.ams.fo.geodeci.fr/permits',
Deze linkjes kun je misschien beter veranderen naar `example.org/permits` oid

2024-11-07 07:59 UTC, timvanoostrom commented on mocks/routes/parkeren.js
> +    id: 'get-company-active-permit-request',
Ik zou die company/private endpoints combineren.

```
url: `${settings.MOCK_BASE_PATH}/parkeren/:profileType/active_permit_request`,

const profileType = req.params.profileType // mocht je dit nodig hebben..

```

2024-11-07 07:59 UTC, timvanoostrom commented on src/client/AppState.ts
> +  ),
Normaal gesproken voegen we geen aparte AppState secties toe voor specifieke stukjes data. Je zou dat dan toevoegen aan `PARKEREN` zoiets als:

```
PARKEREN: apiPristineResult({
  isKnown: true/false,
  vergunningen: [],
  vergunningsAanvragen: []
})
```

Oid.

2024-11-07 14:46 UTC, OscarBakker commented on src/server/services/parkeren/parkeren.ts
> +   */
stond in de ticket dat we die later doen

2024-11-07 14:46 UTC, OscarBakker commented on src/server/services/parkeren/parkeren.ts
> +  console.log(hasPermitRequests, 'hasPermitRequests');
pfff

2024-11-07 14:54 UTC, OscarBakker commented on src/client/config/themas.ts
> +          (!isLoading(PARKEREN) && FeatureToggle.parkerenPatroonC))
sweet

2024-11-07 15:50 UTC, timvanoostrom requested changes

2024-11-07 19:38 UTC, timvanoostrom requested changes

2024-11-07 19:38 UTC, timvanoostrom commented on src/server/services/parkeren/parkeren.ts
> +  );
Om de boel te versnellen kun je dit ook tegelijk opvragen met `Promise.all()`

2024-11-07 19:38 UTC, timvanoostrom commented on src/server/services/parkeren/parkeren.ts
> +  const hasPermits = (clientProductsResponse?.content?.data?.length ?? 0) > 0;
```suggestion
  const hasPermits = !!clientProductsResponse?.content?.data?.length;
```

2024-11-07 19:38 UTC, timvanoostrom commented on src/server/services/parkeren/parkeren.ts
> +    (permitRequestsResponse?.content?.data?.length ?? 0) > 0;
```suggestion
  const hasPermitRequests =
    !!permitRequestsResponse?.content?.data?.length;
```

2024-11-08 11:50 UTC, timvanoostrom approved these changes

2024-11-08 12:09 UTC, merged