Mijn-9880-Bug - Add features check + test,
Amsterdam/mijn-amsterdam-frontend pull request #1667
Opened 2024-12-16 08:44 UTC by timvanoostrom

2024-12-17 08:38 UTC, RoanPaulus approved these changes
Cool

2024-12-17 09:05 UTC, TerryvanWalen requested changes

2024-12-17 09:05 UTC, TerryvanWalen commented on src/server/services/home.ts
>  export async function fetchMyLocation(
Wat gebeurt er in deze functie? Ik merk aan de returnType dat er iets mis gaat. Volgens mij kan dit een stuk simpeler maar ben benieuwd of ik iets mis?

```suggestion
const {content: commercialAddresses} = await fetchCommercial(
  requestID,
  authProfileAndToken
);

if (authProfileAndToken.profile.profileType === 'commercial') {
  return apiSuccessResult(commercialAddresses.filter((location) => location !== null))
}

const {content: privateAddresses} = await fetchPrivate(
  requestID,
  authProfileAndToken
);

const locations: BAGData[] = [
  ...(privateAddresses || []),
  ...(commercialAddresses || []),
].filter((location) => location !== null)

if (locations.length === 0) {
  return apiErrorResult('Could not fetch locations.', null);
}

return apiSuccessResult(locations)
```

2024-12-17 09:10 UTC, TerryvanWalen commented on src/server/services/home.ts
>  export async function fetchMyLocation(
Als je ReturnType kleiner wordt dan wordt ook de logica waarmee de calling functie rekening moet houden simpler/minder.

2024-12-17 09:17 UTC, timvanoostrom commented on src/server/services/adoptable-trash-containers.test.ts
> +describe('fetchAdoptableTrashContainers', () => {
Deze functie haalt alle afvalcontainer op, checked of deze in de buurt liggen en bouwt een tip als deze er zijn.

Ik heb een test toegevoegd: `should return no tips if filteredFeatures length is 0` Is dat wat je mist?

2024-12-17 09:20 UTC, TerryvanWalen commented on src/server/services/home.ts
>  export async function fetchMyLocation(
In plaats van unpack or empty array kan je natuurlijk ook nog:
```
const locations = [[privateAddresses], [commercialAddresses]].flat(2).filter(location => location  !== null)
```
Maar ik vind zelf de unpack or empty methode beter te begrijpen

2024-12-17 09:27 UTC, TerryvanWalen commented on src/server/services/adoptable-trash-containers.test.ts
> +describe('fetchAdoptableTrashContainers', () => {
Ik zie nu de `lat + 1` daar dus dan test deze volgens mij wat ik bedoel. Ik begreep niet dat dit getest werd in deze test aan de hand van de naam (zonder domeinkennis). Als dat voor jou duidelijk is dan is het goed

2024-12-18 09:30 UTC, TerryvanWalen approved these changes

2024-12-18 09:34 UTC, merged