MIJN-9884-feature/Conditionally set note headers
Amsterdam/mijn-amsterdam-frontend pull request #1684
Opened 2024-12-19 14:37 UTC by OscarBakker

2025-01-02 12:33 UTC, RoanPaulus requested changes

2025-01-02 12:33 UTC, RoanPaulus commented on .github/workflows/release-notification.yml
> +          fi
Cool dit lost het probleem op van al die headers zonder paragrafen.
Dit draait gewoon als een bash script toch? Ik zou hier een functie makkelijker begrijpen dus misschien dit:

```suggestion
        append_to_github_output() {
          if [ -s "$1.txt" ]; then
            echo "$1<<EOF" >> "$GITHUB_OUTPUT"
            cat "$1.txt" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
          fi
        }

        append_to_github_output 'chores'
        append_to_github_output 'features'
        append_to_github_output 'bugs'
        append_to_github_output 'mijn'
```

2025-01-07 09:40 UTC, RoanPaulus approved these changes

2025-01-07 09:44 UTC, RoanPaulus commented
Het stukje bash heb ik getest alleen weet niet hoe ik dit makkelijk test met de gehele workflow. Maarja we gaan toch even met de genereer knop dit doen toch?

2025-01-07 16:12 UTC, timvanoostrom approved these changes

2025-01-07 16:12 UTC, merged