Mijn 9631 3 fe en be realiseren contactmoment uit sf
Amsterdam/mijn-amsterdam-frontend pull request #1688
Opened 2024-12-30 13:15 UTC by Anouk91

2025-01-06 20:37 UTC, Anouk91 commented on src/client/pages/Profile/useContactmomenten.hook.tsx
> +        external={(menuItem.to as string).startsWith('http') ? true : false}
Weet niet of dit de beste manier is?

2025-01-12 10:54 UTC, timvanoostrom submitted a review, later dismissed

2025-01-13 13:06 UTC, RoanPaulus requested changes

2025-01-13 13:06 UTC, RoanPaulus commented on src/server/services/salesforce/contactmomenten.ts
> +}
```suggestion
function encryptBsn(bsn: string) {
  throw Error('TODO: Not implemented, waiting for encryption method to be known')
  return bsn;
}
```

2025-01-13 13:06 UTC, RoanPaulus commented on src/server/services/salesforce/contactmomenten.ts
> +}
Is denk ik veiliger voordat we de featuretoggle aanzetten en vergeten deze te implementeren

2025-01-13 15:42 UTC, timvanoostrom commented on src/server/services/salesforce/contactmomenten.ts
> +}
Eens

2025-01-13 15:43 UTC, timvanoostrom commented on src/client/pages/Profile/private/ProfilePrivate.tsx
> +  return (
Kan weg.

2025-01-13 15:53 UTC, RoanPaulus approved these changes

2025-01-13 16:06 UTC, merged