Mijn 3181 toeristische verhuur 3
Amsterdam/mijn-amsterdam-frontend pull request #537
Opened 2021-06-01 09:12 UTC by MokumJ

2021-06-01 09:32 UTC, timvanoostrom commented on src/client/pages/ToeristischeVerhuur/ToeristischeVerhuur.tsx
> +    const items = content.vergunningen
Je kunt ook eerst voor alle type vergunningen de transformatie uitvoeren (date format, title slicing) en daarna groeperen.

```
const allVergunningen = content.vergunningen.map(transform);
const group1 = allVergunningen.map(byTypes(['a', 'b']));
const group2 = allVergunningen.map(byTypes(['c', 'd']));
```

2021-06-01 09:38 UTC, timvanoostrom commented on src/client/pages/ToeristischeVerhuurDetail/ToeristischeVerhuurDetail.tsx
> +        {Vergunning
Deze ternary is niet nodig, de `getHeaderTitle` functie heeft een default 'Onbekende Toeristische verhuur' wanneer het caseType niet bepaald kan worden. Zodoende staat er altijd een titel.

2021-06-01 09:40 UTC, timvanoostrom commented on src/server/services/generated.ts
> -      fetchToeristischeVerhuurGenerated(sessionID, passthroughRequestHeaders),
Waarom heb je het hier weggehaald? Geen meldingen/recent cases meer?

2021-06-01 09:46 UTC, MokumJ commented on src/server/services/generated.ts
> -      fetchToeristischeVerhuurGenerated(sessionID, passthroughRequestHeaders),
Ja dat was een bevinding vanuit de FAT. Ik check zo nog even dubbel met Micha

2021-06-03 08:41 UTC, timvanoostrom requested changes

2021-06-03 08:41 UTC, timvanoostrom commented on src/client/pages/ToeristischeVerhuur/ToeristischeVerhuur.tsx
> +          <p>
Dit levert een lege `<p/>` tag op wanneer je geen actueal(BB)vergunningen hebt.

2021-06-03 08:41 UTC, timvanoostrom commented on src/client/pages/ToeristischeVerhuur/ToeristischeVerhuur.tsx
> +              <>
Waarvoor gebruik je hier een fragment? Misschien is het toffer om te zorgen dat `actualVergunningen` altijd een array is. Dan hoef je geen length checks te doen en kun je af met:

```
<p>
{actualVergunningen.map(...)}
{actualBBVergunningen.map(...)}
</p>

2021-06-03 08:41 UTC, timvanoostrom commented on src/client/pages/ToeristischeVerhuur/ToeristischeVerhuur.tsx
> +                    <Linkd external={true} href={vergunning.link.to}>
Dit zijn geen externe links. Wanneer de link **niet extern** is wordt er een react-router link gebruikt.

2021-06-04 11:08 UTC, timvanoostrom commented on src/server/services/generated.ts
> -      fetchToeristischeVerhuurGenerated(sessionID, passthroughRequestHeaders),
Ah I see, dit staat bij commercial.

2021-06-08 13:01 UTC, timvanoostrom approved these changes

2021-06-08 13:41 UTC, merged