Mijn 3696 usabilla knop
Amsterdam/mijn-amsterdam-frontend pull request #607
Opened 2021-09-08 09:16 UTC by MokumJ

2021-09-09 13:01 UTC, timvanoostrom requested changes
Jesse, usePhoneScreen werkt naar mijn weten prima op een telefoon. Heb je het ook daadwerkelijk gecheckt op je mobiel?

Verder kun je best iets doen als:

```
 const usabillaID = isPhoneScreen
          ? USABILLA_ID_MOBILE
          : USABILLA_ID_DESKTOP;
        (window as any).usabilla_live = lightningjs.require(
          'usabilla_live',
          `https://w.usabilla.com/${usabillaID}.js`
        );
```

usabilla.js ff aanpassen door bovenstaande regels daaruit te slopen.

2021-09-13 07:57 UTC, MokumJ commented
En waar haar ik lightningjs dan vandaan? Deze is undefined in onze bundel.

Het probleem met de use-media query is dat hij default naar false dus dat er altijd een beginnende instance van usabilla inlaad waar usePhoneScreen false is en dus altijd de desktop inlaad. Vandaar de boolean bij het inladen van het script die checkt naar hasScreen. 

Ik heb het inderdaad getest op mobiel, nu gaat alles goed.

2021-09-13 08:21 UTC, timvanoostrom commented
In het usabilla.js script zit lightningjs, ietwat cryptisch:

```
 var o = 'lightningjs',
      k = (window[o] = g(o));
    k.require = g;
    k.modules = c;
```

Volgens mij zou zoiets moeten werken zonder al die changes aan media query behandeling.

```
export function useUsabilla() {
  const [isScriptLoaded] = useScript('/js/usabilla.js', false, true, IS_AP);
  const isPhoneScreen = usePhoneScreen();

  useEffect(() => {
    if (isScriptLoaded) {
      const lightningjs = (window as any).lightningjs;
      if (lightningjs) {
        const usabillaID = isPhoneScreen
          ? USABILLA_ID_MOBILE
          : USABILLA_ID_DESKTOP;
        (window as any).usabilla_live = lightningjs.require(
          'usabilla_live',
          `https://w.usabilla.com/${usabillaID}.js`
        );
        waitForUsabillaLiveInWindow()
          .then(() => {
            (window as any).usabilla_live('data', {
              custom: {
                MatomoVisitorId: (
                  window as any
                ).Matomo?.getTracker().getVisitorId(),
              },
            });
          })
          .catch((error) => {
            Sentry.captureException(error, {
              extra: {
                waitForTimeout: true,
              },
            });
          });
      } else {
        Sentry.captureMessage(
          'Usabilla could not be loaded, lightningjs not found.'
        );
      }
    }
  }, [isScriptLoaded, isPhoneScreen]);
}
```

2021-09-13 08:32 UTC, timvanoostrom commented
Het klopt overigens dat de query in eerste instantie `false` retourneert op mobiel. Dat is niet heel netjes. Kennelijk heeft dat met SSR te maken oid. https://github.com/streamich/use-media/pull/29 Het lijkt mij echter beter om dan een beter dependency te vinden als replacement voor `usePhoneScreen()`

2021-09-13 08:36 UTC, MokumJ commented
Check, ik zal even het internet rondspeuren. Ik mijn persoonlijke projecten gebruik ik ook use-media. Inmiddels niet meer een heel erg gemaintainede package.. Ben je het verder wel eens met het gebruik van context voor de mediaQueries?

2021-09-13 09:01 UTC, timvanoostrom commented
Nee in eerste instantie lijkt dat me overbodig. Wat verbeter/verduidelijk je hier precies mee? 

Mocht je toch een globale state willen gebruiken kun je beter iets ontwikkelen met `useAtom()` 

Maar, waarvoor zou je een globale state willen hebben voor die hooks? Die native functies `window.matchMedia(...)` zijn snel genoeg lijkt mij

2021-09-13 14:38 UTC, closed without merging