data
Amsterdam/mijn-amsterdam-frontend pull request #660
Opened 2021-11-24 10:52 UTC by MokumJ

2021-11-24 14:06 UTC, MokumJ commented
TODO: 
- right sso links
- logic for commercial priviate

2021-11-25 13:52 UTC, timvanoostrom requested changes

2021-11-25 13:52 UTC, timvanoostrom commented on src/client/config/menuItems.ts
> +    to: ExternalUrls.EH_SSO_ERFPACHT || '',
```suggestion
    to: ExternalUrls.DIGID_SSO_SUBSIDIE || '',
```

2021-11-25 13:52 UTC, timvanoostrom commented on src/client/config/menuItems.ts
> +    to: ExternalUrls.EH_SSO_ERFPACHT || '',
```suggestion
    to: ExternalUrls.EH_SSO_SUBSIDIE || '',
```

2021-11-25 13:52 UTC, timvanoostrom commented on src/client/hooks/useChapters.ts
> +      return !isLoading(SUBSIDIE) && SUBSIDIE.content?.isKnown === true;
```suggestion
      return !isLoading(SUBSIDIE) && SUBSIDIE.content?.isKnown === true;
      
```

2021-11-25 13:52 UTC, timvanoostrom commented on src/server/config.ts
> +    url: `${BFF_MS_API_BASE_URL}/subsidie`,
```suggestion
    url: `${BFF_MS_API_BASE_URL}/subsidie/summary`,
```

2021-11-25 13:52 UTC, timvanoostrom commented on src/server/services/controller.ts
> +    SUBSIDIE,
Deze niet toch? (zzp'er)

2021-11-25 13:52 UTC, timvanoostrom commented on src/server/services/subsidie.ts
> +  notifications?: MyNotification[];
```suggestion
  notifications: MyNotification[];
```

2021-11-25 13:52 UTC, timvanoostrom commented on src/server/services/subsidie.ts
> +  tips: MyTip[];
```suggestion

```

2021-11-25 13:52 UTC, timvanoostrom commented on src/server/services/subsidie.ts
> +  meldingen: MyNotification[];
```suggestion
  notifications: MyNotification[];
```

2021-11-25 13:52 UTC, timvanoostrom commented on src/server/services/subsidie.ts
> +
```suggestion

}

```

2021-11-25 13:52 UTC, timvanoostrom commented on src/server/services/subsidie.ts
> +
Deze mag weg, ik zorg dat alles spik-en-span bij de BFF aankomt

2021-11-25 13:52 UTC, timvanoostrom commented on src/server/services/subsidie.ts
> +    }),
```suggestion
    getApiConfig('SUBSIDIE'),
```

2021-11-25 13:52 UTC, timvanoostrom commented on src/server/mock-data/json/subsidie.json
> +    "meldingen": [
```suggestion
    "notifications": [
```

2021-11-29 08:42 UTC, MokumJ commented on src/server/services/subsidie.ts
> +
Er zijn nog een paar "custom meldingen" voor zzp-er de teksten hiervoor moeten nog definitief gemaakt worden. Ik wacht hier nog op voor de defintieve versie van het RD

2021-12-02 11:03 UTC, timvanoostrom approved these changes

2021-12-02 11:53 UTC, merged