Mijn 3989 test mijn buurt
Amsterdam/mijn-amsterdam-frontend pull request #668
Opened 2021-12-15 09:38 UTC by MokumJ

2021-12-17 14:30 UTC, timvanoostrom requested changes
Er zijn m.i 2 dingen mis bij deze implementatie.

- Er wordt state gedupliceert. De `mokum` flag hoeft niet gedupliceerd te worden op het locatie object. We hebben al `isMokum(BRP.content)` en `isMokum(KVK.content)` die kun je ook in de front-end gebruiken.
- Het kan zijn dat je adres niet gevonden wordt terwijl je wel bent ingeschreven in Amsterdam
- Als de MKS weer eens kapot is ben je opeens niet meer ingeschreven in Amsterdam

Als je dan toch een tekst wilt tonen hier een suggestie:

Uw adres kan niet worden weergegeven op deze kaart.

2021-12-20 07:42 UTC, MokumJ commented
Hmm ja, het leek mij in eerste instantie overkill om in de frontent de BRP en KVK call aan te roepen.  Maar er wordt natuurlijk niet een extra call gedaan alleen de app state wordt aangeroepen. Dan houdt mijn redenatie geen steek en is het beter om deze appstate in de frontend gewoon uit te lezen inderdaad.

2021-12-20 08:23 UTC, timvanoostrom commented
Yeah, beter mijn andere concerns bespreken we ff in de standup ok?

2021-12-23 14:08 UTC, timvanoostrom approved these changes

2021-12-23 14:08 UTC, merged