MIJN-4048 - Stop tracking 404's
Amsterdam/mijn-amsterdam-frontend pull request #679
Opened 2022-01-05 15:36 UTC by janthijs

2022-01-06 12:40 UTC, timvanoostrom requested changes

2022-01-06 12:40 UTC, timvanoostrom commented on src/client/hooks/usePageChange.ts
> +    const pageFound = title !== NOT_FOUND_TITLE;
```suggestion
    const isPageFound = title !== NOT_FOUND_TITLE;
```

Indien je een boolean variabele definieert, noem het dan: `isPageFound`, `hasError` etc.

2022-01-06 12:40 UTC, timvanoostrom commented on src/client/hooks/usePageChange.ts
> +      if (pageFound) {
```suggestion
      if (isPageFound) {
```

2022-01-07 08:10 UTC, janthijs commented on src/client/hooks/usePageChange.ts
> +    const pageFound = title !== NOT_FOUND_TITLE;
Var hernoemt

2022-01-07 08:11 UTC, timvanoostrom approved these changes

2022-01-07 09:44 UTC, merged