Mijn 4087 - Toevoegen zoeken op adres feature in Mijn Buurt
Amsterdam/mijn-amsterdam-frontend pull request #689
Opened 2022-01-21 10:07 UTC by janthijs

2022-01-27 16:37 UTC, timvanoostrom requested changes
Als dat mixen van de resultaten bij de MA resultaten niet lekker werkt moeten we even verder kijken. Mogelijk moeten we dan iets extra's maken zodat je kunt togglen tussen adres en normaal oid.

En je mag de adressearch overal aanzetten, niet alleen op de kaart.

2022-01-27 16:37 UTC, timvanoostrom commented on src/client/components/Search/useSearch.tsx
> +  ad?: Loadable<SearchEntry[] | null>;
Zou jde resultaten kunnen toevoegen aan de Fuse instantie waar ook de MA resultaten in geladen worden? Ik denk dat dit beter is dan per "type" zoekresultaat onderscheid maken. Het onderscheid is nu:

- Mijn Amsterdam resultaten, iets waar wij zelf wat mee kunnen
- Amsterdam resultaten, alle overige van Amsterdam.nl

Je kunt misschien de top 10 resultaten van de BAG search inmixen. Mogelijk komt er niets naar voren bij een zoek actie omdat er andere, betere?, resultaten zijn (volgens Fuse).

2022-01-28 08:31 UTC, janthijs commented on src/client/components/Search/useSearch.tsx
> +    // TODO: Do we need useMemo?
De code die uitgevoerd wordt is zo triviaal dat je geen verschil gaat merken met of zonder `useMemo`. Het enige wat ik me kan voorstellen waardoor het mogelijk een positief effect heeft is als `staticEntries` enkele tienduizenden entries zou hebben.

2022-01-28 09:18 UTC, timvanoostrom commented on src/client/components/Search/useSearch.tsx
> +    // TODO: Do we need useMemo?
Tja, waar bepaal je de grens voor trivialiteit in dit geval. Als je rekent: 1ms * 400 (400 render cycles) of 1.1ms (1 memoize call). Dan zie je 400ms vs 1.1ms Dat is opzich geen triviaal verschil. Natuurlijk, kijkend naar het grotere geheel geeft het een ander beeld. 

Kijk je nog wat verder:

1.500.000 bezoekers * 400ms vs 1.500.000 bezoekers * 1.1ms

Even kort door de bocht: ((((1500000*400)/1000)/60)/60) = 166.66 uur per jaar cpu tijd.

2022-01-28 09:19 UTC, timvanoostrom commented on src/client/components/Search/useSearch.tsx
> +    // TODO: Do we need useMemo?
Maar misschien is het uitvoeren van die useMemo hook wel zwaarder.. goeie vraag.

2022-01-28 11:00 UTC, janthijs commented on src/client/components/Search/useSearch.tsx
> +    // TODO: Do we need useMemo?
In dit artikel heeft iemand er wat onderzoek naar gedaan: https://webcache.googleusercontent.com/search?q=cache:flXJc-iHMRQJ:https://canimerge.com/should-you-really-use-usememo-in-react-lets-find-out/+&cd=1&hl=en&ct=clnk&gl=uk

TLDR: pas vanaf grote aantallen > 5000 items en veel re-renders heeft het zin om useMemo te gebruiken.

Overigens, als je op deze manier naar CPU tijd gaat kijken moet je zelfs overwegen of we wel of niet React moeten gebruiken. Immers met plain JS besparen we veel(!) meer CPU tijd.

2022-01-28 11:07 UTC, janthijs commented on src/client/components/MyArea/MyAreaDatasets.tsx
> +    if (!isEqual(center, currentCenter) || !isEqual(zoom, currentZoom)) {
De variabele `bbox` is, voorzover ik kan zien, altijd gedefinieerd. Dus met de check zoals die nu is wordt er nooit een `setView` uitgevoerd. Maar ik begrijp je punt en zal even kijken hoe de if statements aan te passen.

2022-01-28 13:54 UTC, timvanoostrom commented on src/client/components/Search/useSearch.tsx
> +    // TODO: Do we need useMemo?
Dat is waar! Ik heb aan het begin van dit project nog de vraag gesteld: Jongens, is het wel nodig om React te gebruiken? Kunnen we niet beter server-side rendering doen? Ik werd toen raar aangekeken :-)

2022-02-01 14:48 UTC, timvanoostrom reviewed
Ziet er wel nice uit dat nock. Vanwaar deze aanpassing?

2022-02-18 10:22 UTC, timvanoostrom approved these changes
De nieuwe hook die ik heb geïntroduceerd `useMapLocations()` moet nog wel getest worden. Daar maak ik een story voor aan.

2022-02-21 08:40 UTC, merged