MIJN 4439 - Redesign van actueel blok op mobiel
Amsterdam/mijn-amsterdam-frontend pull request #721
Opened 2022-03-28 11:53 UTC by janthijs

2022-03-28 11:54 UTC, janthijs commented on src/client/hooks/media.hook.ts
> -    media.addListener(listener);
Functies `addListener` en `removeListener` zijn deprecated.

2022-03-29 09:26 UTC, janthijs commented on src/client/components/MyNotifications/Notification.tsx
> +  const size = useComponentSize(contentRef.current);
Kan dit stuk tot en met r61 in een custom hook?

2022-04-01 08:00 UTC, timvanoostrom requested changes
Ik heb de branch even gestart en zag een paar usability dingetjes die wat beter kunnen.

- Bij het tonen van de Dashboardpagina op de Desktop schuiven de notificatie uit bij first load. Kun je dit effect tegengaan? Dus direct zichtbaar. Check wel even bij Bram of die notificaties niet ook dit design krijgen op de Desktop versie. Volgens mij krijgen zowel mobiel/desktop hetzelfde ontwerp.
- Zou je bij dichtgeklapte notificatie, het hele item "tapbaar" "klikbaar" kunnen maken
- Bij de Actueel overzichtspagina op mobiel is de marge tussen pagination en notificaties te klein
- Bij de Actueel overzichtspagina op mobiel lijnen de Chevron buttons niet aan de rechterkant
- Bonus: Als je begint op Desktop en resized naar mobiel blijven alle notificaties opengeklapt, bonuspunten als ze inklappen

2022-04-19 09:13 UTC, timvanoostrom approved these changes
LGTM

2022-04-19 11:32 UTC, merged