Mijn 4216 klachten backend
Amsterdam/mijn-amsterdam-frontend pull request #749
Opened 2022-05-31 14:06 UTC by janthijs

2022-06-13 17:08 UTC, timvanoostrom requested changes
Het geheel ziet er compleet uit maar in de details heb ik wat suggesties gedaan. De service staat m.i niet helemaal op de goede plek, hierdoor zijn de Typings hier en daar ook niet waterdicht. 

De code suggesties zijn niet getest / missen imports maar het idee is duidelijk. Als je wilt kunnen we hier morgen even doorheen lopen om e.e.a wel/niet te accepteren in de PR.

Ik hoor 't graag.

2022-06-13 17:08 UTC, timvanoostrom commented on src/server/services/simple-connect/subsidies.ts
> +import { fetchService } from './api-service';
Deze kun je verwijderen

2022-06-13 17:14 UTC, timvanoostrom commented on src/server/mock-data/index.ts
>    },
Moet hier niet `[ApiUrls.KLACHTEN]: { .. },` tussen voor de mock-server?

2022-06-13 17:15 UTC, timvanoostrom commented on src/server/services/simple-connect/klachten.test.ts
> +      expect(res).toMatchSnapshot();
Mits de snapshot niet te groot is kun je ook deze gebruiken:
```suggestion
      expect(res).toMatchInlineSnapshot();
```
werkt net wat lekkerder.

2022-06-14 07:45 UTC, janthijs commented on src/client/pages/Klachten/Klachten.tsx
> +  id: 'Klachtnummer', //TODO: is dit de juiste term?
Daar gaan we dan achterkomen. :)

2022-06-14 11:51 UTC, timvanoostrom requested changes

2022-06-14 11:51 UTC, timvanoostrom commented on src/client/pages/KlachtenDetail/KlachtenDetail.test.tsx
> +          'Enige tijd geleden belde ik naar de GGD om een afspraak te maken voor een booster vaccinatie.\nAangezien mijn geboortejaar 1963 is kom ik nog niet in aanmerking voor deze prik. Maar omdat
graag aanpassen ivm inhoud herleidbaar naar persoon

2022-06-14 11:51 UTC, timvanoostrom commented on src/server/mock-data/json/klachten.json
> +{
In deze file graag de omschrijving anonimiseren / verkorten zodat het niet meer herleidbaar naar een persoon. Daarnaast, iemand kan letterlijk de inhoud van zijn klacht herkennen

2022-06-14 11:51 UTC, timvanoostrom commented on src/server/services/klachten/klachten.test.ts
> +          'Geachte mevrouw, meneer,\r\n\r\nZondag 1 mei jl. bezochten mijn vriend en ik met ons 3 jarig dochtertje het Wertheimpark. We stapten ook bij de kinderboerderij naar binnen. Voor we het wis
Wederom, aanpassen ivm herleidbaar naar persoon.

2022-06-14 11:51 UTC, timvanoostrom commented on src/server/services/klachten/klachten.test.ts
> +              "omschrijving": "Dear Amsterdam Municipality,
Ook hier

2022-06-14 11:51 UTC, timvanoostrom commented on src/server/services/klachten/klachten.test.ts
> +        Zondag 1 mei jl. bezochten mijn vriend en ik met ons 3 jarig dochtertje het Wertheimpark. We stapten ook bij de kinderboerderij naar binnen. Voor we het wisten werd ons dochtertje plotseling
En hier

2022-06-14 11:51 UTC, timvanoostrom commented on src/server/services/klachten/klachten.test.ts
> +              "omschrijving": "Enige tijd geleden belde ik naar de GGD om een afspraak te maken voor een booster vaccinatie.
Ook hier

2022-06-14 11:51 UTC, timvanoostrom commented on src/server/services/klachten/klachten.test.ts
> +              "omschrijving": "Op 19 maart heeft de advocaat van mijnheer D. Trump via een brief aan College B&W afdeling zorg gevraagd om noodopvang voor hem. Mijnheer heeft zich gemeld op de locati
En hier

2022-06-14 11:51 UTC, timvanoostrom commented on src/server/services/klachten/klachten.ts
> +          id: id || '',
```suggestion
          id,
```

2022-06-14 11:51 UTC, timvanoostrom commented on src/server/services/klachten/klachten.ts
> +        title: `Klacht ${id || ''}`,
```suggestion
        title: `Klacht ${id}`,
```

2022-06-14 12:06 UTC, timvanoostrom reviewed
Klein dingetje nog.

2022-06-14 12:28 UTC, janthijs commented on src/client/hooks/useChapters.ts
> +      return !isLoading(KLACHTEN) && FeatureToggle.klachtenActive;
Volgens mij is juist de bedoeling dat het thema altijd getoond wordt. De overzichtspagina verwijst namelijk expliciet naar de mogelijkheid om een klacht in te dienen.

2022-06-14 13:12 UTC, janthijs commented on src/client/hooks/useChapters.ts
> +      return !isLoading(KLACHTEN) && FeatureToggle.klachtenActive;
Staat inderdaad anders in het RD, voor nu gelijk getrokken met het RD.

2022-06-14 13:13 UTC, janthijs commented
> Klein dingetje nog.

Notificaties onder actueel zijn nu ook toegevoegd, die had ik nog over het hoofd gezien.

2022-06-14 13:34 UTC, merged