fix: start with re-design
Amsterdam/mijn-amsterdam-frontend pull request #778
Opened 2022-08-22 08:42 UTC by janthijs

2022-08-22 10:55 UTC, janthijs commented on src/client/components/MainHeader/MainHeader.tsx
> +  throw new Error('Fout');
TODO: Remove

2022-08-25 08:15 UTC, timvanoostrom requested changes
Ziet er toch een stuk fijner uit nu!

2022-08-25 08:15 UTC, timvanoostrom commented on src/client/pages/ApplicationError/ApplicationError.tsx
> +          </picture>
Wat mij betreft zet je hier alleen de fallback neer.

2022-08-25 08:15 UTC, timvanoostrom commented on src/client/pages/ApplicationError/ApplicationError.tsx
> +];
Aangezien de content van de footer uit het CMS komt denk ik dat het een matig idee is om die content hier te dupliceren. Ik snap dat de contactmogelijkheden er wel staan maar deze links lijken mij overbodig voor deze pagina. Kun je dat met Bram bespreken?

2022-08-26 09:38 UTC, timvanoostrom approved these changes

2022-08-29 09:20 UTC, merged